service: test-sls-knex

package:
  individually: true

plugins:
  - serverless-bundle

custom:
  bundle:
    sourcemaps: true
    caching: true
    disableForkTsChecker: true
    stats: false
    linting: false
    forceInclude:
      - pg
    externals:
      - all
    packager: npm


provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
